"""New fields in user model

Revision ID: 137f531feabb
Revises: c362f3fd4ee4
Create Date: 2020-07-24 21:18:19.099686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137f531feabb'
down_revision = 'c362f3fd4ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
